name: Build for Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.13

      - name: Verify Emscripten
        run: em++ --version

      - uses: jurplel/install-qt-action@v2
        with:
          version: 6.2.0
          target: wasm-emscripten

      - name: Verify qmake installation
        run: qmake --version

