name: Build for Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.13

      - name: Verify Emscripten
        run: em++ --version

      - name: Install Qt (host)
        uses: jurplel/install-qt-action@v2
        with:
          version: 6.2.0

      - name: Verify qmake (host)
        run: qmake --version

      - name: Build Qt
        run: |
          git clone https://code.qt.io/qt/qt5.git --branch 6.2.0
          cd qt5
          ./init-repository --module-subset=qtbase,qtshadertools,qtdeclarative
          ./configure -xplatform wasm-emscripten -prefix $PWD/qtbase
          cmake --build . -t qtbase -t qtdeclarative
          cd ..

      - name: Build for WebAssembly
        run: |
          ./qt5/qtbase/bin/qmake
          make
